import { Inter } from "next/font/google";
import "./globals.css";
import Interface from "@/components/mainInterface/interface";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "1Stop.app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Interface />
      </body>
    </html>
  );
}
