"use client";
import ControlBar from "@/app/controlsField/controlsBar";
import { DomainsBar } from "@/app/domainsField/domainsField";
import SearchBar from "@/app/searchField/searchField";
import Signup from "@/app/signup/page";
import CreatePost from "@/app/createPost/page";
import Login from "./login/page";
export default function Home() {
  return (
    <>
      {/* <Login />'
      {/* <Interface /> */}
      <Signup />
    </>
  );
}
